create table tb_schedule_session (
    id bigint generated by default as identity,
    create_by varchar(255) not null,
    created_date timestamp(6) not null,
    last_modified_by varchar(255),
    last_modified_date timestamp(6),
    status varchar(255) not null,
    answered boolean not null,
    last_name varchar(255) not null,
    end_date timestamp(6) not null,
    short_description varchar(255) not null,
    start_date timestamp(6) not null,
    patient_id bigint not null,
    psychological_id bigint not null,
    primary key (id)
)

alter table if exists tb_schedule_session add constraint FKkth34umpjvmlcdm1bd9jcd7pr foreign key (patient_id) references tb_patient
alter table if exists tb_schedule_session add constraint FK8kq7g90ysoo1awt96wp60gl41 foreign key (psychological_id) references tb_psychological
