create table tb_association_social_media (
    id bigint generated by default as identity,
    create_by varchar(255) not null,
    created_date timestamp(6) not null,
    last_modified_by varchar(255),
    last_modified_date timestamp(6),
    status varchar(255) not null,
    domain varchar(255),
    facebook varchar(255),
    instagram varchar(255),
    link varchar(255),
    logo varchar(255),
    twitter varchar(255),
    association_id bigint not null,
    primary key (id)
)
--alter table
  --  if exists tb_association_social_media
--add
  --  constraint FKm068og8exm7l782xpj0k5nby1 foreign key (association_id) references tb_association