create table tb_patient_problem (
    id bigint generated by default as identity,
    create_by varchar(255) not null,
    created_date timestamp(6) not null,
    last_modified_by varchar(255),
    last_modified_date timestamp(6),
    status varchar(255) not null,
    description varchar(255),
    evolved boolean not null,
    patient_id bigint not null,
    problem_type_id bigint not null,
    primary key (id)
)