create table tb_patient (
    id bigint generated by default as identity,
    create_by varchar(255) not null,
    created_date timestamp(6) not null,
    last_modified_by varchar(255),
    last_modified_date timestamp(6),
    status varchar(255) not null,
    address varchar(255) not null,
    document_dispatch_date date,
    document_district varchar(255),
    document_id varchar(255),
    email varchar(45) not null,
    fist_name varchar(255) not null,
    gender varchar(255),
    last_name varchar(255) not null,
    marital_status varchar(255),
    mobile varchar(15) not null,
    mothers_name varchar(255),
    phone varchar(15) not null,
    recurrent boolean not null,
    social_id varchar(255),
    social_id_dispatch_date date,
    association_id bigint not null,
    patient_type_id bigint not null,
    primary key (id)
)

--alter table
  --  if exists tb_patient
--add
    --constraint FKan1fekvabr5x6s85c2lawj8n foreign key (association_id) references tb_association
--alter table
  --  if exists tb_patient
--add
  --  constraint FKhkwcoq98vt0jtnhrfaven61i2 foreign key (patient_type_id) references tb_patient_type
--alter table
  --  if exists tb_patient_problem
--add
  --  constraint FKckfv4qxswyf6tx9tpm2oeejq4 foreign key (patient_id) references tb_patient
--alter table
  --  if exists tb_patient_problem
--add
  --  constraint FKis8grc8ld6xjbgr793m86v8o4 foreign key (problem_type_id) references tb_problem_type