create table tb_psychological_company (
    id bigint generated by default as identity,
    create_by varchar(255) not null,
    created_date timestamp(6) not null,
    last_modified_by varchar(255),
    last_modified_date timestamp(6),
    status varchar(255) not null,
    company_id varchar(255),
    name varchar(255),
    psychological_id bigint not null,
    primary key (id)
)