create table tb_psychological_type (
    id bigint generated by default as identity,
    create_by varchar(255) not null,
    created_date timestamp(6) not null,
    last_modified_by varchar(255),
    last_modified_date timestamp(6),
    status varchar(255) not null,
    description varchar(255),
    primary key (id)
)