create table tb_psychological (
    id bigint generated by default as identity,
    create_by varchar(255) not null,
    created_date timestamp(6) not null,
    last_modified_by varchar(255),
    last_modified_date timestamp(6),
    status varchar(255) not null,
    address varchar(255) not null,
    crp varchar(255),
    document_dispatch_date date,
    document_district varchar(255),
    document_id varchar(255),
    email varchar(45) not null,
    fist_name varchar(255),
    gender varchar(255),
    last_name varchar(255),
    marital_status varchar(255),
    mobile varchar(15) not null,
    mothers_name varchar(255),
    phone varchar(15) not null,
    social_id varchar(255),
    social_id_dispatch_date varchar(255),
    student boolean not null,
    association_id bigint not null,
    psychological_speciality_id bigint not null,
    psychological_type_id bigint not null,
    primary key (id)
)

--alter table if exists tb_psychological add constraint FKkh8qa7l9gx2dkrh2sjlev6tbl foreign key (association_id) references tb_association
--alter table if exists tb_psychological add constraint FKg9tle4vmmad7l41sq1uasyj3y foreign key (psychological_speciality_id) references tb_psychological_speciality
--alter table if exists tb_psychological add constraint FKm4pa07l8msrfcoo71dq0b9btt foreign key (psychological_type_id) references tb_psychological_type
--alter table if exists tb_psychological_company add constraint FKmlwpbj1kipb9qasrf7dir4uni foreign key (psychological_id) references tb_psychological
