drop table if exists tb_association cascade
drop table if exists tb_association_social_media cascade
drop table if exists tb_patient cascade
drop table if exists tb_patient_problem cascade
drop table if exists tb_patient_type cascade
drop table if exists tb_problem_type cascade
drop table if exists tb_profile cascade
drop table if exists tb_project cascade
drop table if exists tb_psychological cascade
drop table if exists tb_psychological_company cascade
drop table if exists tb_psychological_speciality cascade
drop table if exists tb_psychological_type cascade
drop table if exists tb_schedule_session cascade
drop table if exists tb_user cascade
drop table if exists tb_user_profile cascade

create table tb_user (
    id bigint generated by default as identity,
    create_by varchar(255) not null,
    created_date timestamp(6) not null,
    last_modified_by varchar(255),
    last_modified_date timestamp(6),
    status varchar(255) not null,
    email varchar(255) not null,
    last_access timestamp(6) not null,
    name varchar(255) not null,
    password varchar(255) not null,
    primary key (id)
)

create table tb_profile (
    id bigint generated by default as identity,
    create_by varchar(255) not null,
    created_date timestamp(6) not null,
    last_modified_by varchar(255),
    last_modified_date timestamp(6),
    status varchar(255) not null,
    role varchar(255),
    primary key (id)
)

create table tb_user_profile (
    user_id bigint not null,
    profile_id bigint not null,
    primary key (user_id, profile_id)
)

--alter table
  --  if exists tb_user_profile
--add
  --  constraint FK2uwdgjns158unpxn49i9rx2m9 foreign key (profile_id) references tb_profile

--alter table
--    if exists tb_user_profile
--add
--    constraint FKs0kmj8h3yp94qhy8s5xb9q86f foreign key (user_id) references tb_user